- id: deploy_celebrer_agent
  type: puppet
  condition: "settings:celebrer.enable_checkbox.value == true"
  role: '*'
  required_for: [deploy_end]
  requires: [rabbitmq]
  parameters:
    puppet_manifest: "puppet/manifests/agent.pp"
    puppet_modules: "puppet/modules:/etc/puppet/modules"
    timeout: 600

- id: create_dir_for_celebrer_agent
  type: shell
  condition: "settings:celebrer.enable_checkbox.value == true"
  role: '*'
  required_for: [deploy_celebrer_agent]
  requires: [rabbitmq]
  parameters:
    cmd: mkdir /etc/celebrer
    timeout: 30
