- id: deploy_celebrer_agent
  type: puppet
  condition: "settings:celebrer.enable_checkbox.value == true"
  role: '*'
  required_for: [post_deployment_end]
  requires: [post_deployment_start]
  parameters:
    puppet_manifest: "puppet/manifests/agent.pp"
    puppet_modules: "puppet/modules"
    timeout: 3600
    cwd: "/"
